### ISSUE TITLE
add python3 support

### ISSUE THREAD

**Issue by mschmidt87** [INM-6/h5py_wrapper#17]
we should make sure this module can be safely run with python2 & 3

**Comment by mschmidt87** [comment]
Useful link: [https://docs.python.org/3/howto/pyporting.html](https://docs.python.org/3/howto/pyporting.html)

**Comment by mschmidt87** [comment]
Started work on this in my branch enhancement/python3.

**Comment by mschmidt87** [comment]
I started a new branch that builds on top of #32 .
Most issues are easy to solve. We will have to exclude the test of the conversion script, because it uses release version 0.0.1, that only supports python 2.7. 
A major thing is the handling of string and unicode , here is a useful resource for this: [https://docs.python.org/3/howto/unicode.html](https://docs.python.org/3/howto/unicode.html)

**Comment by jakobj** [comment]
closed by #59
