### ISSUE TITLE
Enable storage of Python's type long 

### ISSUE THREAD

**Issue by jschuecker** [INM-6/h5py_wrapper#23]
Since Python's long integer type is not a native numpy type it is converted to an object and thus has no native HDF5 equivalent. 

I discussed this with @jakobj: One workaround would be to store it as a string and store the type information and recreate the long type when loading from h5.  @mschmidt87, what do you think?

**Comment by mschmidt87** [comment]
This is related to #11, which I am addressing in my branch "store_valuetype". I just added a commit which should solve this issue. Can you check out the branch and test it?

**Comment by jschuecker** [comment]
This issue is not solved by #11. The problem appear for dictionaries like ` res = {'a': float(10**100)} `. Since it is actually not a current use-case we will not fix this right now.
