### ISSUE TITLE
Better API function names

### ISSUE THREAD

**Issue by jakobj** [INM-6/h5py_wrapper#25]
In my opinion the current function names of the API are not very well chosen. `add_to_h5` and `load_h5` are not particularly intuitive. How about `save` and `load` like in numpy?
This changes the user interface, so it should be well discussed and we would need to add deprecation the current functions for a while before removing the completely.

**Comment by mschmidt87** [comment]
Yes, I agree, `save` and `load` are more intuitive. We can rename the existing functions and add dummy functions with the old names that just call the new functions then.

**Comment by jakobj** [comment]
👍

**Comment by mschmidt87** [comment]
Then I assume that the functions with the deprecated names don't need any documentation anymore, right?

**Comment by jakobj** [comment]
Hmm. Maybe a hint to check the documentation for the new functions?
