### ISSUE TITLE
Benchmark wrapper in comparison with release 0.0.1 and work on speed

### ISSUE THREAD

**Issue by mschmidt87** [INM-6/h5py_wrapper#34]
I did a quick speed test of the current master (25834fbc60c08f9a116d80447c1afdd24336da7b) with release version 0.0.1 and discovered a significant slow down of the loading routine.

We should do some proper benchmarking, investigate bottlenecks that we apparently introduced and think about solutions. Either we can improve the speed of the implementation in general or we could provide options to the user to e.g. circumvent the time-consuming type-checking in the loading routine.

**Comment by mschmidt87** [comment]
I found that the new implementation of `_load_custom_shape` led to a significant decrease of performance. This is fixed by #35 .

**Comment by mschmidt87** [comment]
I discovered another bottleneck and removed it in #32 , because my new solution works only if value types are stored.

Also, I found that line 275 of wrapper.py takes a lot of time. Do you remember the reason to add this check? I can't think of a possible case where this check returns False, because to my understanding, h5py always stores a value in a dataset. Even if you call `h5py.create_dataset('..', data=None), it requires you to provide a shape and then stores a zero array with the given shape.

**Comment by jakobj** [comment]
Fixed. closing.
