### ISSUE TITLE
supported data types not consistent?

### ISSUE THREAD

**Issue by zbarni** [INM-6/h5py_wrapper#57]
The following code runs (I'm able to save and load):
```
import h5py_wrapper as h5w
import numpy as np

d = { 'np_int64': [ np.int64(10) ] }

h5w.save('file.name', d, write_mode='w')
h5w.load('file.name')
```

However, if I don't put the `np.int64(10)` value in a list, so `d = { 'np_int64': np.int64(10) }`, I get an error when trying to load the file:

> NotImplementedError: Unsupported data type: int64.

I think it's because the list of supported data types is not complete (`valuetype_dict`), although this shouldn't represent a problem since it's possible to save the values..

**Comment by zbarni** [comment]
Adding `'int64': 'np.int64',` to `valuetype_dict` solves the problem. Might be worth to consider extending that dictionary.

**Comment by mschmidt87** [comment]
Thank you for reporting this. Would be willing to create a pull request with this easy extension?

**Comment by zbarni** [comment]
Sure, I'll add numpy.float64 as well and possibly other types.
