### ISSUE TITLE
Specification of path within hdf5 file inconsistent between load and save function

### ISSUE THREAD

**Issue by mschmidt87** [INM-6/h5py_wrapper#60]
Both while loading from and saving to a file, the user can specify paths within the hdf5 file. They are specified with keyword arguments that are called differently in the `load` and `save` function:

`save(filename, d, write_mode='a', overwrite_dataset=False, resize=False, dict_label='', compression=None)`

`load(filename, path='', lazy=False)`

So, we have `dict_path` in the `save` function and `path` in the load function. In my opinion, we should name the arguments consistently across the two function and opt for calling it `path`.

This will of course break user code so we should only include this in the next major release.

**Comment by jakobj** [comment]
Agreed, `path` sounds good. Could we use a similar strategy as, e.g., numpy: show a deprecation warning when people use `dict_label` and add an additional keyword `path` to `save` already now? That way we could introduce this already now and people are aware that this will change in the future, but their old code still works.
